# Question 1

In [1]:
print ('Hello World!')


Hello World!


# Question 2

In [12]:
for x in range(10):
    if x < 5:
        print(x)

0
1
2
3
4


# Question 3 

In [8]:
print(type('100'))
print(type(float('100')))
print(float('100'), type(float('100')))

<class 'str'>
<class 'float'>
100.0 <class 'float'>


# Question 4

In [12]:
value = None
print(type(value))

<class 'NoneType'>


# Question 5


In [27]:
x=-0.05
print(round(x), round(x, 1), round(x, 2))

0 -0.1 -0.05


# Question 6


In [39]:
name=input ('you, I need your name, NOW!')
age= input ('please tell me your age')

print ('My name is ' + name + ' and I am ' + age + ' years old!')

you, I need your name, NOW! Mia
please tell me your age 35


My name is Mia and I am 35 years old!


# Question 7

In [72]:
import numpy as np
Matrix = np.arange(1,17).reshape((4, 4))
print(Matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# Question 8

In [78]:
sumr0 = np.sum(Matrix[0,:])
stdc1 = np.std(Matrix[:,1])
ele01 = Matrix[0,1]
print(sumr0)
print(stdc1)
print(ele01)

10
4.47213595499958
2


# Question 9

In [98]:
import numpy as np
matrix = np.zeros ((3, 4))
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
